### PR TITLE
[FIX] Typo

### PR DESCRIPTION
**Pull request by donut87**
Monacost -> Manacost

### CODE REVIEW

**Comment by alotau** [comment]
Fun fact:  Mona was my second favorite character on "Who's the Boss?"  Another fun fact:  This was the first thing I thought of when I saw "Monacost".

**Comment by donut87** [comment]
Why only second favorite? According to Barney (HIMYM) she actually IS the Boss ;-)

**Comment by alotau** [comment]
Apparently you are not familiar with the effect Alyssa Milano might have had on a boy living through the mid-to-late 80's.

**Comment by donut87** [comment]
I see. Apperently I do cause it was screened here during the 90s again. I just somehow forgot ;-)

**Pull request merged**
